> # Relatório de Acompanhamento GT-Ativo Imobilizado Setor Lapa

In [60]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\dougl\appdata\local\programs\python\python314\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\dougl\appdata\local\programs\python\python314\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [61]:
%pip install pandas xlrd

Requirement already satisfied: pandas in c:\users\dougl\appdata\local\programs\python\python314\lib\site-packages (3.0.3)
Requirement already satisfied: xlrd in c:\users\dougl\appdata\local\programs\python\python314\lib\site-packages (2.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\dougl\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dougl\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dougl\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\dougl\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [62]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\dougl\appdata\local\programs\python\python314\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\dougl\appdata\local\programs\python\python314\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Esse código é um script clássico de análise inicial de dados usando a biblioteca Pandas no Python. Em resumo, ele está localizando um arquivo de inventário de bens e mostrando uma "amostra grátis" do que tem dentro dele.

In [63]:
import pandas as pd

# Read the Excel file from the workspace volume
excel_path = r'C:\Users\dougl\OneDrive\Databricks+CCB+-+2026\Relatório de Bens Imobilizado.xlsx'

df = pd.read_excel(excel_path)
display(df.head(10))

,Código,Nome,Fornecedor,Localidade,Conta,Nº Documento,Dependência,Dt. Aquisição,Vl. Aquisição,Vl. Deprec.,Vl. Atual,Status
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,MANUTEN\nAO DE MAQUINAS LTDA,BR 21-0056,1101,10722.0,COZINHA,2010-11-23,130.0,130.0,0,Ativo
5,21-0056 / 000007,56 - EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,GALERIA,2010-12-09,95.0,95.0,0,Ativo
6,21-0056 / 000008,56 - EXTINTOR EXTINTOR AP 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,ATRIO ESQUERDO,2010-12-09,95.0,95.0,0,Ativo
7,21-0056 / 000010,56 - EXTINTOR EXTINTOR PO QUIMICO 4 KG,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,COZINHA,2010-12-09,95.0,95.0,0,Ativo
8,21-0056 / 000011,"8 - ARMÁRIO ARMARIO COZINHA 8 PORTAS 3,84X2,40...",NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,0,Depreciado
9,21-0056 / 000012,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,SALAO DE CULTO,1999-12-31,1.0,1.0,0,Depreciado

Este código segue exatamente a mesma lógica do anterior, mas com um foco diferente: em vez de olhar para o que a empresa tem (bens imobilizados), ele está carregando a lista de onde as coisas estão ou como a empresa está organizada.

In [64]:
# Read the Excel file from the workspace volume
excel_path = 'C:/Users/dougl/OneDrive/Databricks+CCB+-+2026/cadastro_dependencias.xlsx'

df = pd.read_excel(excel_path)
display(df.head(10))

,Casa de Oração,Endereço
0,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042"
1,BR 21-0083 - LAPA,"RUA JOÃO PEREIRA, 319"
2,BR 21-0088 - PARQUE ANHANGUERA - PERUS,"RUA AMADEU CAEGO MONTEIRO, 58"
3,BR 21-0091 - PARQUE DA LAPA,"AVENIDA DIÓGENES RIBEIRO DE LIMA, 3170"
4,BR 21-0093 - PARQUE MORRO DOCE - PERUS,"RUA ALBERT JANSEN, 15"
5,BR 21-0099 - PERUS,"RUA PRESIDENTE VARGAS, 111"
6,BR 21-0100 - VILA PERUS - PERUS,"RUA ANTÔNIO MAIA, 62"
7,BR 21-0101 - JARDIM DO RUSSO - PERUS,"RUA FIGUEIREDO COIMBRA, 170,"
8,BR 21-0102 - JARDIM SÃO PAULO - VILA MALVINA -...,"RUA ENGENHEIRO AUGUSTO DURANTE, 389"
9,BR 21-0103 - VILA PIAUÍ,"RUA TEIXEIRA SOARES, 45"

Este código está realizando um processo de limpeza e extração de dados (muitas vezes chamado de parsing). Ele pega uma informação "misturada" em uma única coluna e a divide em três partes distintas.

In [65]:
import pandas as pd

excel_path = 'C:/Users/dougl/OneDrive/Databricks+CCB+-+2026/cadastro_dependencias.xlsx'
df = pd.read_excel(excel_path)

# Dividir a coluna 'Casa de Oração' em três colunas
df[['col1', 'col2', 'col3']] = df['Casa de Oração'].str.extract(r'^(BR \d{2}-\d{4})\s*(-)\s*(.*)$')

display(df.head(10))

,Casa de Oração,Endereço,col1,col2,col3
0,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,-,JARDIM DAS BANDEIRAS
1,BR 21-0083 - LAPA,"RUA JOÃO PEREIRA, 319",BR 21-0083,-,LAPA
2,BR 21-0088 - PARQUE ANHANGUERA - PERUS,"RUA AMADEU CAEGO MONTEIRO, 58",BR 21-0088,-,PARQUE ANHANGUERA - PERUS
3,BR 21-0091 - PARQUE DA LAPA,"AVENIDA DIÓGENES RIBEIRO DE LIMA, 3170",BR 21-0091,-,PARQUE DA LAPA
4,BR 21-0093 - PARQUE MORRO DOCE - PERUS,"RUA ALBERT JANSEN, 15",BR 21-0093,-,PARQUE MORRO DOCE - PERUS
5,BR 21-0099 - PERUS,"RUA PRESIDENTE VARGAS, 111",BR 21-0099,-,PERUS
6,BR 21-0100 - VILA PERUS - PERUS,"RUA ANTÔNIO MAIA, 62",BR 21-0100,-,VILA PERUS - PERUS
7,BR 21-0101 - JARDIM DO RUSSO - PERUS,"RUA FIGUEIREDO COIMBRA, 170,",BR 21-0101,-,JARDIM DO RUSSO - PERUS
8,BR 21-0102 - JARDIM SÃO PAULO - VILA MALVINA -...,"RUA ENGENHEIRO AUGUSTO DURANTE, 389",BR 21-0102,-,JARDIM SÃO PAULO - VILA MALVINA - PERUS
9,BR 21-0103 - VILA PIAUÍ,"RUA TEIXEIRA SOARES, 45",BR 21-0103,-,VILA PIAUÍ

Este código é a continuação da limpeza de dados que você começou no passo anterior. Ele serve para organizar e "limpar" a tabela, removendo informações inúteis e dando nomes claros para as colunas que você criou.

In [66]:
df = df.drop(columns=['col2']).rename(columns={'col1': 'codco', 'col3': 'nomeco'})
display(df.head(10))

,Casa de Oração,Endereço,codco,nomeco
0,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
1,BR 21-0083 - LAPA,"RUA JOÃO PEREIRA, 319",BR 21-0083,LAPA
2,BR 21-0088 - PARQUE ANHANGUERA - PERUS,"RUA AMADEU CAEGO MONTEIRO, 58",BR 21-0088,PARQUE ANHANGUERA - PERUS
3,BR 21-0091 - PARQUE DA LAPA,"AVENIDA DIÓGENES RIBEIRO DE LIMA, 3170",BR 21-0091,PARQUE DA LAPA
4,BR 21-0093 - PARQUE MORRO DOCE - PERUS,"RUA ALBERT JANSEN, 15",BR 21-0093,PARQUE MORRO DOCE - PERUS
5,BR 21-0099 - PERUS,"RUA PRESIDENTE VARGAS, 111",BR 21-0099,PERUS
6,BR 21-0100 - VILA PERUS - PERUS,"RUA ANTÔNIO MAIA, 62",BR 21-0100,VILA PERUS - PERUS
7,BR 21-0101 - JARDIM DO RUSSO - PERUS,"RUA FIGUEIREDO COIMBRA, 170,",BR 21-0101,JARDIM DO RUSSO - PERUS
8,BR 21-0102 - JARDIM SÃO PAULO - VILA MALVINA -...,"RUA ENGENHEIRO AUGUSTO DURANTE, 389",BR 21-0102,JARDIM SÃO PAULO - VILA MALVINA - PERUS
9,BR 21-0103 - VILA PIAUÍ,"RUA TEIXEIRA SOARES, 45",BR 21-0103,VILA PIAUÍ

Este código é a conclusão da lógica que vínhamos discutindo. Ele está realizando um Cruzamento de Dados (Merge/Join) para consolidar as informações de dois arquivos diferentes em uma única tabela mestre. 
O Resultado Final
O df_merged agora é uma tabela poderosa que contém, em uma única linha:
Os dados do item imobilizado (Descrição, Valor, Data).
O código da localidade (vinda de df_bens).
O nome completo da Casa de Oração e outras informações de endereço (vindas de df_dep).

In [67]:
import pandas as pd

# Ler os arquivos Excel (Caminhos Locais Corrigidos)
excel_bens = 'C:/Users/dougl/OneDrive/Databricks+CCB+-+2026/Relatório de Bens Imobilizado.xlsx'
excel_dep = 'C:/Users/dougl/OneDrive/Databricks+CCB+-+2026/cadastro_dependencias.xlsx'

df_bens = pd.read_excel(excel_bens)
df_dep = pd.read_excel(excel_dep)

# Transformações necessárias para criar 'codco' em df_dep
# Dividir a coluna 'Casa de Oração' em três colunas temporárias
df_dep[['col1', 'col2', 'col3']] = df_dep['Casa de Oração'].str.extract(r'^(BR \d{2}-\d{4})\s*(-)\s*(.*)$')
# Remover 'col2' e renomear as colunas
df_dep = df_dep.drop(columns=['col2']).rename(columns={'col1': 'codco', 'col3': 'nomeco'})

# Mesclar os DataFrames usando 'Localidade' (df_bens) e 'codco' (df_dep)
df_merged = pd.merge(df_bens, df_dep, left_on='Localidade', right_on='codco', how='left')

display(df_merged.head(10))

,Código,Nome,Fornecedor,Localidade,Conta,Nº Documento,Dependência,Dt. Aquisição,Vl. Aquisição,Vl. Deprec.,Vl. Atual,Status,Casa de Oração,Endereço,codco,nomeco
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,MANUTEN\nAO DE MAQUINAS LTDA,BR 21-0056,1101,10722.0,COZINHA,2010-11-23,130.0,130.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
5,21-0056 / 000007,56 - EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,GALERIA,2010-12-09,95.0,95.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
6,21-0056 / 000008,56 - EXTINTOR EXTINTOR AP 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,ATRIO ESQUERDO,2010-12-09,95.0,95.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
7,21-0056 / 000010,56 - EXTINTOR EXTINTOR PO QUIMICO 4 KG,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,COZINHA,2010-12-09,95.0,95.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
8,21-0056 / 000011,"8 - ARMÁRIO ARMARIO COZINHA 8 PORTAS 3,84X2,40...",NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
9,21-0056 / 000012,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,SALAO DE CULTO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS

Nesta etapa final, o script padroniza as chaves de ligação para garantir que a associação entre os bens e seus respectivos grupos administrativos seja 100% precisa:
Padronização de Código: Utiliza Regex (r'^BR\s*') para remover o prefixo "BR" e eventuais espaços no início da coluna codco. Isso é necessário porque a base de grupos utiliza apenas o numeral (ex: 11-1234), enquanto a base de dependências contém o prefixo (ex: BR 11-1234).
Integração Final (Left Join): Cruza a tabela mestre (df_merged) com a tabela de setores (df_grupos).
Chave Esquerda: codcoSemBR (Código limpo).
Chave Direita: Codigo CO (ID original do arquivo de grupos).
Resultado: Criação do df_final, que agora possui a hierarquia completa: Bem Imobilizado > Localidade > Setor Regional.

In [68]:
import pandas as pd

# Ler os arquivos Excel
excel_bens = 'C:/Users/dougl/OneDrive/Databricks+CCB+-+2026/Relatório de Bens Imobilizado.xlsx'
excel_dep = 'C:/Users/dougl/OneDrive/Databricks+CCB+-+2026/cadastro_dependencias.xlsx'

df_bens = pd.read_excel(excel_bens)
df_dep = pd.read_excel(excel_dep)

# Transformações necessárias para criar 'codco' em df_dep
# Dividir a coluna 'Casa de Oração' em três colunas temporárias
df_dep[['col1', 'col2', 'col3']] = df_dep['Casa de Oração'].str.extract(r'^(BR \d{2}-\d{4})\s*(-)\s*(.*)$')
# Remover 'col2' e renomear as colunas
df_dep = df_dep.drop(columns=['col2']).rename(columns={'col1': 'codco', 'col3': 'nomeco'})

# Mesclar os DataFrames usando 'Localidade' (df_bens) e 'codco' (df_dep)
df_merged = pd.merge(df_bens, df_dep, left_on='Localidade', right_on='codco', how='left')

display(df_merged.head(10))

,Código,Nome,Fornecedor,Localidade,Conta,Nº Documento,Dependência,Dt. Aquisição,Vl. Aquisição,Vl. Deprec.,Vl. Atual,Status,Casa de Oração,Endereço,codco,nomeco
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,MANUTEN\nAO DE MAQUINAS LTDA,BR 21-0056,1101,10722.0,COZINHA,2010-11-23,130.0,130.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
5,21-0056 / 000007,56 - EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,GALERIA,2010-12-09,95.0,95.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
6,21-0056 / 000008,56 - EXTINTOR EXTINTOR AP 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,ATRIO ESQUERDO,2010-12-09,95.0,95.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
7,21-0056 / 000010,56 - EXTINTOR EXTINTOR PO QUIMICO 4 KG,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,COZINHA,2010-12-09,95.0,95.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
8,21-0056 / 000011,"8 - ARMÁRIO ARMARIO COZINHA 8 PORTAS 3,84X2,40...",NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS
9,21-0056 / 000012,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,SALAO DE CULTO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS

Este código realiza a leitura e a visualização inicial da terceira base de dados do seu projeto, que contém a estrutura de setorização regional.

In [69]:
excel_grupos = 'C:/Users/dougl/OneDrive/Databricks+CCB+-+2026/grupos_set_lapa.xlsx'
df_grupos = pd.read_excel(excel_grupos)
display(df_grupos.head(10))

  Codigo CO                                 Nome CO       Grupo
0   21-1491                        12ª SEGUNDA ÁREA  Anhanguera
1   21-0784          CHÁCARA MARIA TRINDADE - PERUS  Anhanguera
2   21-0820  JARDIM ANHANGUERA - MORRO DOCE - PERUS  Anhanguera
3   21-0857                 JARDIM BRITÂNIA - PERUS  Anhanguera
4   21-1423                        JARDIM PAINEIRAS  Anhanguera
5   21-0088               PARQUE ANHANGUERA - PERUS  Anhanguera
6   21-0093               PARQUE MORRO DOCE - PERUS  Anhanguera
7   21-1146    RESIDENCIAL PARQUE ESPERANÇA - PERUS  Anhanguera
8   21-0711                    SOL NASCENTE - PERUS  Anhanguera
9   21-0747               VILA DOS PALMARES - PERUS  Anhanguera

In [70]:
df_merged['codcoSemBR'] = df_merged['codco'].str.replace(r'^BR\s*', '', regex=True)
display(df_merged.head(10))

,Código,Nome,Fornecedor,Localidade,Conta,Nº Documento,Dependência,Dt. Aquisição,Vl. Aquisição,Vl. Deprec.,Vl. Atual,Status,Casa de Oração,Endereço,codco,nomeco,codcoSemBR
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,MANUTEN\nAO DE MAQUINAS LTDA,BR 21-0056,1101,10722.0,COZINHA,2010-11-23,130.0,130.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056
5,21-0056 / 000007,56 - EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,GALERIA,2010-12-09,95.0,95.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056
6,21-0056 / 000008,56 - EXTINTOR EXTINTOR AP 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,ATRIO ESQUERDO,2010-12-09,95.0,95.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056
7,21-0056 / 000010,56 - EXTINTOR EXTINTOR PO QUIMICO 4 KG,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,COZINHA,2010-12-09,95.0,95.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056
8,21-0056 / 000011,"8 - ARMÁRIO ARMARIO COZINHA 8 PORTAS 3,84X2,40...",NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056
9,21-0056 / 000012,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,SALAO DE CULTO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056

Este é o comando que consolida toda a sua análise. Ele une a base de Bens + Localidades (que você já tinha no df_merged) com a base de Setores/Grupos.

O que este código faz exatamente:
A Junção (Merge): Ele procura o código da igreja (sem o "BR") na coluna codcoSemBR da sua tabela principal e tenta achar o par correspondente na coluna Codigo CO da tabela de grupos.

A Lógica how='left': Esta é a parte mais segura do código. Ela garante que nenhum item do seu relatório de bens seja apagado, mesmo que aquela igreja específica não conste na planilha de grupos. Se não houver correspondência, as informações do setor aparecerão como NaN (vazio).

A Criação do df_final: Agora você tem um DataFrame completo. Cada linha representa um bem imobilizado, mas agora traz colunas adicionais como o nome do setor, regional ou supervisor (dependendo do que houver no arquivo da Lapa).

In [71]:
df_final = pd.merge(df_merged, df_grupos, left_on='codcoSemBR', right_on='Codigo CO', how='left')
display(df_final.head(10))

,Código,Nome,Fornecedor,Localidade,Conta,Nº Documento,Dependência,Dt. Aquisição,Vl. Aquisição,Vl. Deprec.,Vl. Atual,Status,Casa de Oração,Endereço,codco,nomeco,codcoSemBR,Codigo CO,Nome CO,Grupo
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,MANUTEN\nAO DE MAQUINAS LTDA,BR 21-0056,1101,10722.0,COZINHA,2010-11-23,130.0,130.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa
5,21-0056 / 000007,56 - EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,GALERIA,2010-12-09,95.0,95.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa
6,21-0056 / 000008,56 - EXTINTOR EXTINTOR AP 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,ATRIO ESQUERDO,2010-12-09,95.0,95.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa
7,21-0056 / 000010,56 - EXTINTOR EXTINTOR PO QUIMICO 4 KG,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,COZINHA,2010-12-09,95.0,95.0,0,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa
8,21-0056 / 000011,"8 - ARMÁRIO ARMARIO COZINHA 8 PORTAS 3,84X2,40...",NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa
9,21-0056 / 000012,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,SALAO DE CULTO,1999-12-31,1.0,1.0,0,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa

O que o seu padrão Regex r'^[\w\d\.]+\s*-\s*' faz:
^: Garante que a substituição comece do início da linha.

[\w\d\.]+: Procura por uma sequência de letras, números ou pontos (o \. que você adicionou é ótimo para códigos como 101.001).

\s*-\s*: Localiza o hífen, removendo também qualquer espaço que exista antes ou depois dele.

'' (vazio): Substitui tudo isso por nada, efetivamente "apagando" o código.

In [72]:
df_final['nome_sem_codigo'] = df_final['Nome'].str.replace(r'^[\w\d\.]+\s*-\s*', '', regex=True)
display(df_final.head(20))

,Código,Nome,Fornecedor,Localidade,Conta,Nº Documento,Dependência,Dt. Aquisição,Vl. Aquisição,Vl. Deprec.,...,Status,Casa de Oração,Endereço,codco,nomeco,codcoSemBR,Codigo CO,Nome CO,Grupo,nome_sem_codigo
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 X 0,30"
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 X 0,27"
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE MAD...
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE MAD...
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,MANUTEN\nAO DE MAQUINAS LTDA,BR 21-0056,1101,10722.0,COZINHA,2010-11-23,130.0,130.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA BEBEDO...
5,21-0056 / 000007,56 - EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,GALERIA,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.
6,21-0056 / 000008,56 - EXTINTOR EXTINTOR AP 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,ATRIO ESQUERDO,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR AP 10 L.
7,21-0056 / 000010,56 - EXTINTOR EXTINTOR PO QUIMICO 4 KG,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,COZINHA,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR PO QUIMICO 4 KG
8,21-0056 / 000011,"8 - ARMÁRIO ARMARIO COZINHA 8 PORTAS 3,84X2,40...",NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMÁRIO ARMARIO COZINHA 8 PORTAS 3,84X2,40X0,59"
9,21-0056 / 000012,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,SALAO DE CULTO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE MAD...
10,21-0056 / 000013,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
11,21-0056 / 000014,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
12,21-0056 / 000015,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
13,21-0056 / 000016,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
14,21-0056 / 000017,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
15,21-0056 / 000018,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
16,21-0056 / 000019,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
17,21-0056 / 000020,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
18,21-0056 / 000021,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
19,21-0056 / 000022,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO

Este é o passo final para garantir a integridade e a padronização total dos seus dados. O que você está fazendo aqui é a remoção de acentos e caracteres especiais (normalização) da coluna que você acabou de limpar.

In [73]:
import unicodedata

df_final['nome_sem_codigo'] = df_final['nome_sem_codigo'].apply(
    lambda x: unicodedata.normalize('NFKD', x).encode('ASCII', 'ignore').decode('ASCII') if isinstance(x, str) else x
)
display(df_final.head(20))

,Código,Nome,Fornecedor,Localidade,Conta,Nº Documento,Dependência,Dt. Aquisição,Vl. Aquisição,Vl. Deprec.,...,Status,Casa de Oração,Endereço,codco,nomeco,codcoSemBR,Codigo CO,Nome CO,Grupo,nome_sem_codigo
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 X 0,30"
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 X 0,27"
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,MANUTEN\nAO DE MAQUINAS LTDA,BR 21-0056,1101,10722.0,COZINHA,2010-11-23,130.0,130.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BEBEDOURO D'AGUA / PURIFICADOR DE AGUA BEBEDO...
5,21-0056 / 000007,56 - EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,GALERIA,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.
6,21-0056 / 000008,56 - EXTINTOR EXTINTOR AP 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,ATRIO ESQUERDO,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR AP 10 L.
7,21-0056 / 000010,56 - EXTINTOR EXTINTOR PO QUIMICO 4 KG,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,COZINHA,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR PO QUIMICO 4 KG
8,21-0056 / 000011,"8 - ARMÁRIO ARMARIO COZINHA 8 PORTAS 3,84X2,40...",NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO COZINHA 8 PORTAS 3,84X2,40X0,59"
9,21-0056 / 000012,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,SALAO DE CULTO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
10,21-0056 / 000013,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
11,21-0056 / 000014,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
12,21-0056 / 000015,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
13,21-0056 / 000016,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
14,21-0056 / 000017,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
15,21-0056 / 000018,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
16,21-0056 / 000019,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
17,21-0056 / 000020,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
18,21-0056 / 000021,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
19,21-0056 / 000022,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO

In [74]:
nao_comeca_com_letra = df_final[~df_final['nome_sem_codigo'].str.match(r'^[A-Za-z]', na=False)]
display(nao_comeca_com_letra)

,Código,Nome,Fornecedor,Localidade,Conta,Nº Documento,Dependência,Dt. Aquisição,Vl. Aquisição,Vl. Deprec.,...,Status,Casa de Oração,Endereço,codco,nomeco,codcoSemBR,Codigo CO,Nome CO,Grupo,nome_sem_codigo
263,21-0056 / 000318,OT-1 - OUTROS - MÓVEIS E UTENSÍLIOS CARRINHO C...,FORMULARIO 22,BR 21-0056,1101,5606.0,LAVANDERIA,2016-10-18,1.00,1.00,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,1 - OUTROS - MOVEIS E UTENSILIOS CARRINHO CARG...
827,21-0083 / 001158,ME-123 - EVA,LIDER FLEX DISTRIBUIDORA DE ACESSÓRIOS PARA CA...,BR 21-0083,1101,1960.0,ESPAÇO INFANTIL,2025-11-06,21.14,1.26,...,Ativo,BR 21-0083 - LAPA,"RUA JOÃO PEREIRA, 319",BR 21-0083,LAPA,21-0083,21-0083,LAPA,Lapa,123 - EVA
828,21-0083 / 001159,ME-123 - EVA,LIDER FLEX DISTRIBUIDORA DE ACESSÓRIOS PARA CA...,BR 21-0083,1101,1960.0,ESPAÇO INFANTIL,2025-11-06,21.14,1.26,...,Ativo,BR 21-0083 - LAPA,"RUA JOÃO PEREIRA, 319",BR 21-0083,LAPA,21-0083,21-0083,LAPA,Lapa,123 - EVA
829,21-0083 / 001160,ME-123 - EVA,LIDER FLEX DISTRIBUIDORA DE ACESSÓRIOS PARA CA...,BR 21-0083,1101,1960.0,ESPAÇO INFANTIL,2025-11-06,21.14,1.26,...,Ativo,BR 21-0083 - LAPA,"RUA JOÃO PEREIRA, 319",BR 21-0083,LAPA,21-0083,21-0083,LAPA,Lapa,123 - EVA
830,21-0083 / 001161,ME-123 - EVA,LIDER FLEX DISTRIBUIDORA DE ACESSÓRIOS PARA CA...,BR 21-0083,1101,1960.0,ESPAÇO INFANTIL,2025-11-06,21.14,1.26,...,Ativo,BR 21-0083 - LAPA,"RUA JOÃO PEREIRA, 319",BR 21-0083,LAPA,21-0083,21-0083,LAPA,Lapa,123 - EVA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8936,21-1453 / 000009,CR-1015 - ALARME,VOICE DATA SISTEMAS INTEGRADOS,BR 21-1453,1106,323607.0,PADRÃO,2026-06-19,478.82,0.00,...,Ativo,BR 21-1453 - JARDIM SÃO RICARDO,"RUA JOSÉ CORREIA LIMA, 333,",BR 21-1453,JARDIM SÃO RICARDO,21-1453,NaN,NaN,NaN,1015 - ALARME
8937,21-1453 / 000010,CR-1015 - ALARME,VOICE DATA SISTEMAS INTEGRADOS,BR 21-1453,1106,323607.0,PADRÃO,2026-06-19,478.82,0.00,...,Ativo,BR 21-1453 - JARDIM SÃO RICARDO,"RUA JOSÉ CORREIA LIMA, 333,",BR 21-1453,JARDIM SÃO RICARDO,21-1453,NaN,NaN,NaN,1015 - ALARME
8974,21-1453 / 000047,CR-17 - BANCADA PARA BANHEIRO,D&S MARMORE LTDA,BR 21-1453,1101,87.0,PADRÃO,2026-02-24,1400.00,46.68,...,Ativo,BR 21-1453 - JARDIM SÃO RICARDO,"RUA JOSÉ CORREIA LIMA, 333,",BR 21-1453,JARDIM SÃO RICARDO,21-1453,NaN,NaN,NaN,17 - BANCADA PARA BANHEIRO
9018,21-1491 / 000037,CR-20 - ESPELHO PARA BANHEIRO,GILMARCOS ALVES DE SOUZAR ME,BR 21-1491,1101,108.0,PADRÃO,2024-08-14,200.00,36.74,...,Ativo,BR 21-1491 - 12ª SEGUNDA ÁREA,"RUA ADONIRAN BARBOSA, 28 - QUADRA 8 - LOTE 35,",BR 21-1491,12ª SEGUNDA ÁREA,21-1491,21-1491,12ª SEGUNDA ÁREA,Anhanguera,20 - ESPELHO PARA BANHEIRO
9019,21-1491 / 000038,CR-20 - ESPELHO PARA BANHEIRO,GILMARCOS ALVES DE SOUZAR ME,BR 21-1491,1101,108.0,TEMPLO,2024-08-14,150.00,27.50,...,Ativo,BR 21-1491 - 12ª SEGUNDA ÁREA,"RUA ADONIRAN BARBOSA, 28 - QUADRA 8 - LOTE 35,",BR 21-1491,12ª SEGUNDA ÁREA,21-1491,21-1491,12ª SEGUNDA ÁREA,Anhanguera,20 - ESPELHO PARA BANHEIRO

In [75]:
# O nome correto da coluna é 'nome_sem_codigo', não 'nome_sem_codgio'.
# Verifique se está usando o nome correto da coluna ao aplicar a normalização.

import unicodedata

df_final['nome_sem_codigo'] = df_final['nome_sem_codigo'].apply(
    lambda x: unicodedata.normalize('NFKD', x).encode('ASCII', 'ignore').decode('ASCII') if isinstance(x, str) else x
)
display(df_final.head(20))

,Código,Nome,Fornecedor,Localidade,Conta,Nº Documento,Dependência,Dt. Aquisição,Vl. Aquisição,Vl. Deprec.,...,Status,Casa de Oração,Endereço,codco,nomeco,codcoSemBR,Codigo CO,Nome CO,Grupo,nome_sem_codigo
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 X 0,30"
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 X 0,27"
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,MANUTEN\nAO DE MAQUINAS LTDA,BR 21-0056,1101,10722.0,COZINHA,2010-11-23,130.0,130.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BEBEDOURO D'AGUA / PURIFICADOR DE AGUA BEBEDO...
5,21-0056 / 000007,56 - EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,GALERIA,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.
6,21-0056 / 000008,56 - EXTINTOR EXTINTOR AP 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,ATRIO ESQUERDO,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR AP 10 L.
7,21-0056 / 000010,56 - EXTINTOR EXTINTOR PO QUIMICO 4 KG,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,COZINHA,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR PO QUIMICO 4 KG
8,21-0056 / 000011,"8 - ARMÁRIO ARMARIO COZINHA 8 PORTAS 3,84X2,40...",NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO COZINHA 8 PORTAS 3,84X2,40X0,59"
9,21-0056 / 000012,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,SALAO DE CULTO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
10,21-0056 / 000013,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
11,21-0056 / 000014,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
12,21-0056 / 000015,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
13,21-0056 / 000016,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
14,21-0056 / 000017,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
15,21-0056 / 000018,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
16,21-0056 / 000019,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
17,21-0056 / 000020,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
18,21-0056 / 000021,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
19,21-0056 / 000022,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO

In [76]:
import re

# Remove números e caracteres especiais do início da string, mantendo apenas letras no início
df_final['nome_sem_codigo'] = df_final['nome_sem_codigo'].apply(
    lambda x: re.sub(r'^[^A-Za-z]+', '', x) if isinstance(x, str) else x
)
display(df_final.head(20))

,Código,Nome,Fornecedor,Localidade,Conta,Nº Documento,Dependência,Dt. Aquisição,Vl. Aquisição,Vl. Deprec.,...,Status,Casa de Oração,Endereço,codco,nomeco,codcoSemBR,Codigo CO,Nome CO,Grupo,nome_sem_codigo
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 X 0,30"
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 X 0,27"
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,MANUTEN\nAO DE MAQUINAS LTDA,BR 21-0056,1101,10722.0,COZINHA,2010-11-23,130.0,130.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BEBEDOURO D'AGUA / PURIFICADOR DE AGUA BEBEDO...
5,21-0056 / 000007,56 - EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,GALERIA,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.
6,21-0056 / 000008,56 - EXTINTOR EXTINTOR AP 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,ATRIO ESQUERDO,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR AP 10 L.
7,21-0056 / 000010,56 - EXTINTOR EXTINTOR PO QUIMICO 4 KG,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,COZINHA,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR PO QUIMICO 4 KG
8,21-0056 / 000011,"8 - ARMÁRIO ARMARIO COZINHA 8 PORTAS 3,84X2,40...",NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO COZINHA 8 PORTAS 3,84X2,40X0,59"
9,21-0056 / 000012,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,SALAO DE CULTO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
10,21-0056 / 000013,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
11,21-0056 / 000014,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
12,21-0056 / 000015,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
13,21-0056 / 000016,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
14,21-0056 / 000017,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
15,21-0056 / 000018,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
16,21-0056 / 000019,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
17,21-0056 / 000020,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
18,21-0056 / 000021,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
19,21-0056 / 000022,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO

In [77]:
nao_comeca_com_letra = df_final[~df_final['nome_sem_codigo'].str.match(r'^[A-Za-z]', na=False)]
if not nao_comeca_com_letra.empty:
    display(nao_comeca_com_letra)
else:
    print('Nenhuma linha encontrada: todas começam com letra.')

Nenhuma linha encontrada: todas começam com letra.

In [78]:
# Rename columns with invalid characters for compatibility
rename_map = {
    'Nº Documento': 'N_Documento',
    'Dt. Aquisição': 'Dt_Aquisicao',
    'Vl. Aquisição': 'Vl_Aquisicao',
    'Vl. Deprec.': 'Vl_Deprec',
    'Vl. Atual': 'Vl_Atual',
    'Casa de Oração': 'Casa_de_Oracao',
    'Codigo CO': 'Codigo_CO',
    'Nome CO': 'Nome_CO'
}
df_final_fixed = df_final.rename(columns=rename_map)
df_final_pandas = df_final_fixed
display(df_final_pandas.head(10))

,Código,Nome,Fornecedor,Localidade,Conta,N_Documento,Dependência,Dt_Aquisicao,Vl_Aquisicao,Vl_Deprec,...,Status,Casa_de_Oracao,Endereço,codco,nomeco,codcoSemBR,Codigo_CO,Nome_CO,Grupo,nome_sem_codigo
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 X 0,30"
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 X 0,27"
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,MANUTEN\nAO DE MAQUINAS LTDA,BR 21-0056,1101,10722.0,COZINHA,2010-11-23,130.0,130.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BEBEDOURO D'AGUA / PURIFICADOR DE AGUA BEBEDO...
5,21-0056 / 000007,56 - EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,GALERIA,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.
6,21-0056 / 000008,56 - EXTINTOR EXTINTOR AP 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,ATRIO ESQUERDO,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR AP 10 L.
7,21-0056 / 000010,56 - EXTINTOR EXTINTOR PO QUIMICO 4 KG,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,COZINHA,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR PO QUIMICO 4 KG
8,21-0056 / 000011,"8 - ARMÁRIO ARMARIO COZINHA 8 PORTAS 3,84X2,40...",NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO COZINHA 8 PORTAS 3,84X2,40X0,59"
9,21-0056 / 000012,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,SALAO DE CULTO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...

In [79]:
# Visualizar as primeiras linhas do DataFrame final
display(df_final_pandas.head(20))

,Código,Nome,Fornecedor,Localidade,Conta,N_Documento,Dependência,Dt_Aquisicao,Vl_Aquisicao,Vl_Deprec,...,Status,Casa_de_Oracao,Endereço,codco,nomeco,codcoSemBR,Codigo_CO,Nome_CO,Grupo,nome_sem_codigo
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 X 0,30"
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 X 0,27"
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,ATRIO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,MANUTEN\nAO DE MAQUINAS LTDA,BR 21-0056,1101,10722.0,COZINHA,2010-11-23,130.0,130.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BEBEDOURO D'AGUA / PURIFICADOR DE AGUA BEBEDO...
5,21-0056 / 000007,56 - EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,GALERIA,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR AGUA PRESSURIZADA 10 L.
6,21-0056 / 000008,56 - EXTINTOR EXTINTOR AP 10 L.,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,ATRIO ESQUERDO,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR AP 10 L.
7,21-0056 / 000010,56 - EXTINTOR EXTINTOR PO QUIMICO 4 KG,DAVI BIROCHI EXTINTORES ME,BR 21-0056,1101,4984.0,COZINHA,2010-12-09,95.0,95.0,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,EXTINTOR EXTINTOR PO QUIMICO 4 KG
8,21-0056 / 000011,"8 - ARMÁRIO ARMARIO COZINHA 8 PORTAS 3,84X2,40...",NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,"ARMARIO ARMARIO COZINHA 8 PORTAS 3,84X2,40X0,59"
9,21-0056 / 000012,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,NENHUM,BR 21-0056,1101,1.0,SALAO DE CULTO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,BANCO DE MADEIRA / GENUFLEXORIO BANCO DE MAD...
10,21-0056 / 000013,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
11,21-0056 / 000014,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
12,21-0056 / 000015,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
13,21-0056 / 000016,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
14,21-0056 / 000017,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
15,21-0056 / 000018,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
16,21-0056 / 000019,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
17,21-0056 / 000020,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
18,21-0056 / 000021,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO
19,21-0056 / 000022,4 - CADEIRA CADEIRA DE PLASTICO,NENHUM,BR 21-0056,1101,1.0,COZINHA,1999-12-31,1.0,1.0,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,CADEIRA CADEIRA DE PLASTICO

In [80]:
# Exibir a contagem total de registros
print(f"Total de registros: {len(df_final_pandas)}")

Total de registros: 9136

In [81]:
# Equivalente Pandas para a consulta SQL (filtrar itens que parecem ser órgãos):
organ_df = df_final_pandas[df_final_pandas['nome_sem_codigo'].str.contains(r'org.o', case=False, na=False, regex=True)]
display(organ_df)

,Código,Nome,Fornecedor,Localidade,Conta,N_Documento,Dependência,Dt_Aquisicao,Vl_Aquisicao,Vl_Deprec,...,Status,Casa_de_Oracao,Endereço,codco,nomeco,codcoSemBR,Codigo_CO,Nome_CO,Grupo,nome_sem_codigo
201,21-0056 / 000239,5 - GRADE DE MADEIRA P/ ÓRGÃO GRADE DE MADEIRA...,GUIMARAES COMERCIAL INSTR LTDA,BR 21-0056,1101,5533.0,SALAO DE CULTO,2005-01-27,750.00,750.00,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,GRADE DE MADEIRA P/ ORGAO GRADE DE MADEIRA P/ ...
207,21-0056 / 000248,21 - ÓRGÃOS E INSTRUMENTOS ÓRGÃO COM BANQUETA ...,NENHUM,BR 21-0056,1102,1.0,SALAO DE CULTO,1999-12-31,1.00,1.00,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,ORGAOS E INSTRUMENTOS ORGAO COM BANQUETA YAMAH...
341,21-0056 / 000486,21 - ÓRGÃOS E INSTRUMENTOS TOKAY MD750,KYODDAY COM. E IND. DE INSTRUM. MUSICAIS,BR 21-0056,1102,19711.0,SALAO DE CULTO,2023-10-16,15180.00,4301.00,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,ORGAOS E INSTRUMENTOS TOKAY MD750
369,21-0083 / 000020,21 - ÓRGÃOS E INSTRUMENTOS ORGAO COM BANQUETA ...,NENHUM,BR 21-0083,1102,1.0,SECRETARIA,1999-12-31,1.00,1.00,...,Depreciado,BR 21-0083 - LAPA,"RUA JOÃO PEREIRA, 319",BR 21-0083,LAPA,21-0083,21-0083,LAPA,Lapa,ORGAOS E INSTRUMENTOS ORGAO COM BANQUETA MINAMI
472,21-0083 / 000163,5 - GRADE DE MADEIRA P/ ÓRGÃO GRADE DE MADEIRA...,NENHUM,BR 21-0083,1101,1.0,SALAO DE CULTO,1999-12-31,1.00,1.00,...,Depreciado,BR 21-0083 - LAPA,"RUA JOÃO PEREIRA, 319",BR 21-0083,LAPA,21-0083,21-0083,LAPA,Lapa,GRADE DE MADEIRA P/ ORGAO GRADE DE MADEIRA P/ ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8878,21-1426 / 001087,21 - ÓRGÃOS E INSTRUMENTOS ORGAO ELETRONICO TOKAI,JORGE GUIMARAES DE SOUZA,BR 21-1426,1102,801.0,SALAO DE CULTO,2012-06-23,2650.00,2650.00,...,Ativo,BR 21-1426 - VILA ANASTÁCIO,"RUA MARTINHO DE CAMPOS, 179",BR 21-1426,VILA ANASTÁCIO,21-1426,21-1426,VILA ANASTÁCIO,Lapa,ORGAOS E INSTRUMENTOS ORGAO ELETRONICO TOKAI
8903,21-1443 / 000019,21.001 - ORGAO C/ BANQUETA RHONES LIZ PLUS,NaN,BR 21-1443,1102,142.0,TEMPLO,2025-02-06,1.00,0.16,...,Ativo,BR 21-1443 - VILA CAIUBA,"RUA ANTÔNIO CÂNDIDO DE ALVARENGA, 522,",BR 21-1443,VILA CAIUBA,21-1443,21-1443,VILA CAIUBA,Perus,ORGAO C/ BANQUETA RHONES LIZ PLUS
8938,21-1453 / 000011,21 - ÓRGÃOS E INSTRUMENTOS,GUIMARAES COMERCIAL INSTR LTDA,BR 21-1453,1102,4613.0,PADRÃO,2003-04-11,2750.00,2750.00,...,Ativo,BR 21-1453 - JARDIM SÃO RICARDO,"RUA JOSÉ CORREIA LIMA, 333,",BR 21-1453,JARDIM SÃO RICARDO,21-1453,NaN,NaN,NaN,ORGAOS E INSTRUMENTOS
9025,21-1491 / 000044,21.001 - ORGAO C/ BANQUETA TOKAI MODELO YX200II,NaN,BR 21-1491,1102,142.0,SALAO DE CULTO,2025-08-14,6059.25,504.90,...,Ativo,BR 21-1491 - 12ª SEGUNDA ÁREA,"RUA ADONIRAN BARBOSA, 28 - QUADRA 8 - LOTE 35,",BR 21-1491,12ª SEGUNDA ÁREA,21-1491,21-1491,12ª SEGUNDA ÁREA,Anhanguera,ORGAO C/ BANQUETA TOKAI MODELO YX200II
9060,21-1598 / 000036,21 - ÓRGÃOS E INSTRUMENTOS ORGAO COM BANQUETA ...,NENHUM,BR 21-1598,1102,1.0,SALAO DE CULTO,1999-12-31,1.00,1.00,...,Depreciado,BR 21-1598 - VILA DOS PALMARES II,"RUA MANOEL FIEL FILHO, 16,",BR 21-1598,VILA DOS PALMARES II,21-1598,21-1598,VILA DOS PALMARES II,Anhanguera,ORGAOS E INSTRUMENTOS ORGAO COM BANQUETA MINAMI

Este código SQL tem o objetivo de identificar quais Casas de Oração não possuem órgãos registrados na base de dados.

In [82]:
# Equivalente Pandas para a consulta SQL (filtrar itens que parecem ser órgãos):
organ_df = df_final_pandas[df_final_pandas['nome_sem_codigo'].str.contains(r'org.o', case=False, na=False, regex=True)]
display(organ_df)

,Código,Nome,Fornecedor,Localidade,Conta,N_Documento,Dependência,Dt_Aquisicao,Vl_Aquisicao,Vl_Deprec,...,Status,Casa_de_Oracao,Endereço,codco,nomeco,codcoSemBR,Codigo_CO,Nome_CO,Grupo,nome_sem_codigo
201,21-0056 / 000239,5 - GRADE DE MADEIRA P/ ÓRGÃO GRADE DE MADEIRA...,GUIMARAES COMERCIAL INSTR LTDA,BR 21-0056,1101,5533.0,SALAO DE CULTO,2005-01-27,750.00,750.00,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,GRADE DE MADEIRA P/ ORGAO GRADE DE MADEIRA P/ ...
207,21-0056 / 000248,21 - ÓRGÃOS E INSTRUMENTOS ÓRGÃO COM BANQUETA ...,NENHUM,BR 21-0056,1102,1.0,SALAO DE CULTO,1999-12-31,1.00,1.00,...,Depreciado,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,ORGAOS E INSTRUMENTOS ORGAO COM BANQUETA YAMAH...
341,21-0056 / 000486,21 - ÓRGÃOS E INSTRUMENTOS TOKAY MD750,KYODDAY COM. E IND. DE INSTRUM. MUSICAIS,BR 21-0056,1102,19711.0,SALAO DE CULTO,2023-10-16,15180.00,4301.00,...,Ativo,BR 21-0056 - JARDIM DAS BANDEIRAS,"RUA APINAJÉS, 2042",BR 21-0056,JARDIM DAS BANDEIRAS,21-0056,21-0056,JARDIM DAS BANDEIRAS,Lapa,ORGAOS E INSTRUMENTOS TOKAY MD750
369,21-0083 / 000020,21 - ÓRGÃOS E INSTRUMENTOS ORGAO COM BANQUETA ...,NENHUM,BR 21-0083,1102,1.0,SECRETARIA,1999-12-31,1.00,1.00,...,Depreciado,BR 21-0083 - LAPA,"RUA JOÃO PEREIRA, 319",BR 21-0083,LAPA,21-0083,21-0083,LAPA,Lapa,ORGAOS E INSTRUMENTOS ORGAO COM BANQUETA MINAMI
472,21-0083 / 000163,5 - GRADE DE MADEIRA P/ ÓRGÃO GRADE DE MADEIRA...,NENHUM,BR 21-0083,1101,1.0,SALAO DE CULTO,1999-12-31,1.00,1.00,...,Depreciado,BR 21-0083 - LAPA,"RUA JOÃO PEREIRA, 319",BR 21-0083,LAPA,21-0083,21-0083,LAPA,Lapa,GRADE DE MADEIRA P/ ORGAO GRADE DE MADEIRA P/ ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8878,21-1426 / 001087,21 - ÓRGÃOS E INSTRUMENTOS ORGAO ELETRONICO TOKAI,JORGE GUIMARAES DE SOUZA,BR 21-1426,1102,801.0,SALAO DE CULTO,2012-06-23,2650.00,2650.00,...,Ativo,BR 21-1426 - VILA ANASTÁCIO,"RUA MARTINHO DE CAMPOS, 179",BR 21-1426,VILA ANASTÁCIO,21-1426,21-1426,VILA ANASTÁCIO,Lapa,ORGAOS E INSTRUMENTOS ORGAO ELETRONICO TOKAI
8903,21-1443 / 000019,21.001 - ORGAO C/ BANQUETA RHONES LIZ PLUS,NaN,BR 21-1443,1102,142.0,TEMPLO,2025-02-06,1.00,0.16,...,Ativo,BR 21-1443 - VILA CAIUBA,"RUA ANTÔNIO CÂNDIDO DE ALVARENGA, 522,",BR 21-1443,VILA CAIUBA,21-1443,21-1443,VILA CAIUBA,Perus,ORGAO C/ BANQUETA RHONES LIZ PLUS
8938,21-1453 / 000011,21 - ÓRGÃOS E INSTRUMENTOS,GUIMARAES COMERCIAL INSTR LTDA,BR 21-1453,1102,4613.0,PADRÃO,2003-04-11,2750.00,2750.00,...,Ativo,BR 21-1453 - JARDIM SÃO RICARDO,"RUA JOSÉ CORREIA LIMA, 333,",BR 21-1453,JARDIM SÃO RICARDO,21-1453,NaN,NaN,NaN,ORGAOS E INSTRUMENTOS
9025,21-1491 / 000044,21.001 - ORGAO C/ BANQUETA TOKAI MODELO YX200II,NaN,BR 21-1491,1102,142.0,SALAO DE CULTO,2025-08-14,6059.25,504.90,...,Ativo,BR 21-1491 - 12ª SEGUNDA ÁREA,"RUA ADONIRAN BARBOSA, 28 - QUADRA 8 - LOTE 35,",BR 21-1491,12ª SEGUNDA ÁREA,21-1491,21-1491,12ª SEGUNDA ÁREA,Anhanguera,ORGAO C/ BANQUETA TOKAI MODELO YX200II
9060,21-1598 / 000036,21 - ÓRGÃOS E INSTRUMENTOS ORGAO COM BANQUETA ...,NENHUM,BR 21-1598,1102,1.0,SALAO DE CULTO,1999-12-31,1.00,1.00,...,Depreciado,BR 21-1598 - VILA DOS PALMARES II,"RUA MANOEL FIEL FILHO, 16,",BR 21-1598,VILA DOS PALMARES II,21-1598,21-1598,VILA DOS PALMARES II,Anhanguera,ORGAOS E INSTRUMENTOS ORGAO COM BANQUETA MINAMI

O código cria um novo DataFrame para o Depósito do Santa Terezinha contendo apenas as linhas referentes à "Vila Santa Terezinha - Pirituba" e exibe o resultado na tela imediatamente.

In [83]:
# Filtrar por depósito específico usando Pandas
df_deposito = df_final_pandas[df_final_pandas['Casa_de_Oracao'] == 'BR 21-1201 - VILA SANTA TEREZINHA - PIRITUBA - DEPÓSITO']
display(df_deposito)

,Código,Nome,Fornecedor,Localidade,Conta,N_Documento,Dependência,Dt_Aquisicao,Vl_Aquisicao,Vl_Deprec,...,Status,Casa_de_Oracao,Endereço,codco,nomeco,codcoSemBR,Codigo_CO,Nome_CO,Grupo,nome_sem_codigo
8027,21-1201 / 000013,1 - BANCO DE MADEIRA / GENUFLEXÓRIO,SET - LAPA - SP,BR 21-1201,1101,22.0,PADRÃO,2018-01-31,1.0,1.0,...,Ativo,BR 21-1201 - VILA SANTA TEREZINHA - PIRITUBA -...,"RUA SILVESTRO PALMA, 609,",BR 21-1201,VILA SANTA TEREZINHA - PIRITUBA - DEPÓSITO,21-1201,NaN,NaN,NaN,BANCO DE MADEIRA / GENUFLEXORIO
8028,21-1201 / 000041,OT-1 - OUTROS - MÓVEIS E UTENSÍLIOS CARRINHO D...,SET - LAPA - SP,BR 21-1201,1101,22.0,PADRÃO,2018-01-31,1.0,1.0,...,Ativo,BR 21-1201 - VILA SANTA TEREZINHA - PIRITUBA -...,"RUA SILVESTRO PALMA, 609,",BR 21-1201,VILA SANTA TEREZINHA - PIRITUBA - DEPÓSITO,21-1201,NaN,NaN,NaN,OUTROS - MOVEIS E UTENSILIOS CARRINHO DE BANCO
8029,21-1201 / 000042,OT-1 - OUTROS - MÓVEIS E UTENSÍLIOS CARRINHO D...,SET - LAPA - SP,BR 21-1201,1101,22.0,PADRÃO,2018-01-31,1.0,1.0,...,Ativo,BR 21-1201 - VILA SANTA TEREZINHA - PIRITUBA -...,"RUA SILVESTRO PALMA, 609,",BR 21-1201,VILA SANTA TEREZINHA - PIRITUBA - DEPÓSITO,21-1201,NaN,NaN,NaN,OUTROS - MOVEIS E UTENSILIOS CARRINHO DE BANCO
8030,21-1201 / 000043,OT-1 - OUTROS - MÓVEIS E UTENSÍLIOS CARRINHO D...,SET - LAPA - SP,BR 21-1201,1101,22.0,PADRÃO,2018-01-31,1.0,1.0,...,Ativo,BR 21-1201 - VILA SANTA TEREZINHA - PIRITUBA -...,"RUA SILVESTRO PALMA, 609,",BR 21-1201,VILA SANTA TEREZINHA - PIRITUBA - DEPÓSITO,21-1201,NaN,NaN,NaN,OUTROS - MOVEIS E UTENSILIOS CARRINHO DE BANCO
8031,21-1201 / 000044,OT-1 - OUTROS - MÓVEIS E UTENSÍLIOS CARRINHO D...,SET - LAPA - SP,BR 21-1201,1101,22.0,PADRÃO,2018-01-31,1.0,1.0,...,Ativo,BR 21-1201 - VILA SANTA TEREZINHA - PIRITUBA -...,"RUA SILVESTRO PALMA, 609,",BR 21-1201,VILA SANTA TEREZINHA - PIRITUBA - DEPÓSITO,21-1201,NaN,NaN,NaN,OUTROS - MOVEIS E UTENSILIOS CARRINHO DE BANCO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8085,21-1201 / 000300,"1 - BANCO DE MADEIRA / GENUFLEXÓRIO 2,66",NaN,BR 21-1201,1101,14.0,PADRÃO,2024-02-10,1.0,0.3,...,Ativo,BR 21-1201 - VILA SANTA TEREZINHA - PIRITUBA -...,"RUA SILVESTRO PALMA, 609,",BR 21-1201,VILA SANTA TEREZINHA - PIRITUBA - DEPÓSITO,21-1201,NaN,NaN,NaN,"BANCO DE MADEIRA / GENUFLEXORIO 2,66"
8086,21-1201 / 000301,"1 - BANCO DE MADEIRA / GENUFLEXÓRIO 2,66",NaN,BR 21-1201,1101,14.0,PADRÃO,2024-02-10,1.0,0.3,...,Ativo,BR 21-1201 - VILA SANTA TEREZINHA - PIRITUBA -...,"RUA SILVESTRO PALMA, 609,",BR 21-1201,VILA SANTA TEREZINHA - PIRITUBA - DEPÓSITO,21-1201,NaN,NaN,NaN,"BANCO DE MADEIRA / GENUFLEXORIO 2,66"
8087,21-1201 / 000302,54 - COFRE COFRE NS 400 LIGHT,NEW SAFES IND MET LTDA.,BR 21-1201,1101,4171.0,PADRÃO,2017-02-24,660.0,627.0,...,Ativo,BR 21-1201 - VILA SANTA TEREZINHA - PIRITUBA -...,"RUA SILVESTRO PALMA, 609,",BR 21-1201,VILA SANTA TEREZINHA - PIRITUBA - DEPÓSITO,21-1201,NaN,NaN,NaN,COFRE COFRE NS 400 LIGHT
8088,21-1201 / 000303,51.010 - TERMOMETRO INFRAVERMELHO TERMOMETRO I...,"LÓGIGO HEALTH & HEALTH, TECN. AUTO. COM., IMP....",BR 21-1201,1101,24578.0,PADRÃO,2020-10-01,85.0,49.7,...,Ativo,BR 21-1201 - VILA SANTA TEREZINHA - PIRITUBA -...,"RUA SILVESTRO PALMA, 609,",BR 21-1201,VILA SANTA TEREZINHA - PIRITUBA - DEPÓSITO,21-1201,NaN,NaN,NaN,TERMOMETRO INFRAVERMELHO TERMOMETRO INFRAVERME...
8089,21-1201 / 000305,61 - CAIXA DE COLETA CAIXA DE COLETA,NENHUM,BR 21-1201,1101,1.0,PADRÃO,1999-12-31,1.0,1.0,...,Depreciado,BR 21-1201 - VILA SANTA TEREZINHA - PIRITUBA -...,"RUA SILVESTRO PALMA, 609,",BR 21-1201,VILA SANTA TEREZINHA - PIRITUBA - DEPÓSITO,21-1201,NaN,NaN,NaN,CAIXA DE COLETA CAIXA DE COLETA

Esse código está escrito em PySpark (a interface Python para Apache Spark) e é tipicamente executado em ambientes de notebooks como Databricks ou Microsoft Fabric/Synapse.

Em resumo: ele carrega uma tabela salva no seu catálogo de dados, escolhe apenas quatro colunas específicas e exibe o resultado na tela de forma interativa.

In [84]:
# Selecionar colunas específicas usando Pandas
df_selected = df_final_pandas[["Código", "Nome", "Dependência", "Dt_Aquisicao"]].copy()
display(df_selected)

,Código,Nome,Dependência,Dt_Aquisicao
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",ATRIO,1999-12-31
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",ATRIO,1999-12-31
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,ATRIO,1999-12-31
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,ATRIO,1999-12-31
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,COZINHA,2010-11-23
...,...,...,...,...
9131,21-1598 / 000107,17 - CAIXA DE SOM,SALAO DE CULTO,1999-12-31
9132,21-1598 / 000108,17 - CAIXA DE SOM,SALAO DE CULTO,2009-08-21
9133,21-1598 / 000109,18 - MICROFONE,SALAO DE CULTO,1999-12-31
9134,21-1598 / 000110,18 - MICROFONE,SALAO DE CULTO,1999-12-31
9135,21-1598 / 000111,18 - MICROFONE,SALAO DE CULTO,1999-12-31

Este código expande o exemplo anterior. Além de ler os dados existentes, ele agora adiciona quatro novas colunas vazias ao DataFrame.

Isso é muito comum quando você está criando um template ou uma planilha para auditoria/inventário, onde um ser humano ou outro processo precisará preencher essas informações posteriormente.

In [85]:
# Criar colunas vazias usando Pandas
df_selected = df_final_pandas[["Código", "Nome", "Dependência", "Dt_Aquisicao"]].copy()
df_selected["Encontrado?"] = ""
df_selected["Etiqueta?"] = ""
df_selected["Nova Localização"] = ""
df_selected["Operação"] = ""
display(df_selected)

,Código,Nome,Dependência,Dt_Aquisicao,Encontrado?,Etiqueta?,Nova Localização,Operação
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",ATRIO,1999-12-31,,,,
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",ATRIO,1999-12-31,,,,
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,ATRIO,1999-12-31,,,,
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,ATRIO,1999-12-31,,,,
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,COZINHA,2010-11-23,,,,
...,...,...,...,...,...,...,...,...
9131,21-1598 / 000107,17 - CAIXA DE SOM,SALAO DE CULTO,1999-12-31,,,,
9132,21-1598 / 000108,17 - CAIXA DE SOM,SALAO DE CULTO,2009-08-21,,,,
9133,21-1598 / 000109,18 - MICROFONE,SALAO DE CULTO,1999-12-31,,,,
9134,21-1598 / 000110,18 - MICROFONE,SALAO DE CULTO,1999-12-31,,,,
9135,21-1598 / 000111,18 - MICROFONE,SALAO DE CULTO,1999-12-31,,,,

Este trecho de código realiza a formatação da data para o padrão brasileiro (Dia/Mês/Ano).

No passo anterior, a data provavelmente estava no formato padrão de banco de dados (ISO: Ano-Mês-Dia). Este código transforma essa visualização para facilitar a leitura humana.

In [86]:
# Formatar data usando Pandas
df_selected["Dt_Aquisicao"] = pd.to_datetime(df_selected["Dt_Aquisicao"], errors='coerce').dt.strftime('%d/%m/%Y')
df_selected["Dt_Aquisicao"] = df_selected["Dt_Aquisicao"].fillna("")
display(df_selected)

,Código,Nome,Dependência,Dt_Aquisicao,Encontrado?,Etiqueta?,Nova Localização,Operação
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",ATRIO,31/12/1999,,,,
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",ATRIO,31/12/1999,,,,
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,ATRIO,31/12/1999,,,,
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,ATRIO,31/12/1999,,,,
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,COZINHA,23/11/2010,,,,
...,...,...,...,...,...,...,...,...
9131,21-1598 / 000107,17 - CAIXA DE SOM,SALAO DE CULTO,31/12/1999,,,,
9132,21-1598 / 000108,17 - CAIXA DE SOM,SALAO DE CULTO,21/08/2009,,,,
9133,21-1598 / 000109,18 - MICROFONE,SALAO DE CULTO,31/12/1999,,,,
9134,21-1598 / 000110,18 - MICROFONE,SALAO DE CULTO,31/12/1999,,,,
9135,21-1598 / 000111,18 - MICROFONE,SALAO DE CULTO,31/12/1999,,,,

In [87]:
# Mesclar usando Pandas
df_selected = df_selected.merge(
    df_final_pandas[["Código", "nomeco"]],
    on="Código",
    how="left"
)
display(df_selected)

,Código,Nome,Dependência,Dt_Aquisicao,Encontrado?,Etiqueta?,Nova Localização,Operação,nomeco
0,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",ATRIO,31/12/1999,,,,,JARDIM DAS BANDEIRAS
1,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",ATRIO,31/12/1999,,,,,JARDIM DAS BANDEIRAS
2,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,ATRIO,31/12/1999,,,,,JARDIM DAS BANDEIRAS
3,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,ATRIO,31/12/1999,,,,,JARDIM DAS BANDEIRAS
4,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,COZINHA,23/11/2010,,,,,JARDIM DAS BANDEIRAS
...,...,...,...,...,...,...,...,...,...
9131,21-1598 / 000107,17 - CAIXA DE SOM,SALAO DE CULTO,31/12/1999,,,,,VILA DOS PALMARES II
9132,21-1598 / 000108,17 - CAIXA DE SOM,SALAO DE CULTO,21/08/2009,,,,,VILA DOS PALMARES II
9133,21-1598 / 000109,18 - MICROFONE,SALAO DE CULTO,31/12/1999,,,,,VILA DOS PALMARES II
9134,21-1598 / 000110,18 - MICROFONE,SALAO DE CULTO,31/12/1999,,,,,VILA DOS PALMARES II
9135,21-1598 / 000111,18 - MICROFONE,SALAO DE CULTO,31/12/1999,,,,,VILA DOS PALMARES II

In [88]:
# Reordenar colunas usando Pandas
cols = ["nomeco"] + [col for col in df_selected.columns if col != "nomeco"]
df_selected = df_selected[cols]
display(df_selected)

,nomeco,Código,Nome,Dependência,Dt_Aquisicao,Encontrado?,Etiqueta?,Nova Localização,Operação
0,JARDIM DAS BANDEIRAS,21-0056 / 000001,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 0,60 X 0,50 ...",ATRIO,31/12/1999,,,,
1,JARDIM DAS BANDEIRAS,21-0056 / 000002,"8 - ARMÁRIO ARMARIO FUNDO BIBLICO 1,50 X 0,90 ...",ATRIO,31/12/1999,,,,
2,JARDIM DAS BANDEIRAS,21-0056 / 000003,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,ATRIO,31/12/1999,,,,
3,JARDIM DAS BANDEIRAS,21-0056 / 000004,1 - BANCO DE MADEIRA / GENUFLEXÓRIO BANCO DE...,ATRIO,31/12/1999,,,,
4,JARDIM DAS BANDEIRAS,21-0056 / 000005,13 - BEBEDOURO D'ÁGUA / PURIFICADOR DE ÁGUA B...,COZINHA,23/11/2010,,,,
...,...,...,...,...,...,...,...,...,...
9131,VILA DOS PALMARES II,21-1598 / 000107,17 - CAIXA DE SOM,SALAO DE CULTO,31/12/1999,,,,
9132,VILA DOS PALMARES II,21-1598 / 000108,17 - CAIXA DE SOM,SALAO DE CULTO,21/08/2009,,,,
9133,VILA DOS PALMARES II,21-1598 / 000109,18 - MICROFONE,SALAO DE CULTO,31/12/1999,,,,
9134,VILA DOS PALMARES II,21-1598 / 000110,18 - MICROFONE,SALAO DE CULTO,31/12/1999,,,,
9135,VILA DOS PALMARES II,21-1598 / 000111,18 - MICROFONE,SALAO DE CULTO,31/12/1999,,,,

In [89]:
# Agrupar em um dicionário usando Pandas
nomeco_list = df_selected["nomeco"].dropna().unique().tolist()
df_selected_dict = {nomeco: df_selected[df_selected["nomeco"] == nomeco] for nomeco in nomeco_list}

In [90]:
import pandas as pd
import os
import shutil
import base64
from IPython.display import HTML, display as ipy_display

# --- 1. CONFIGURAÇÃO E LIMPEZA ---
caminho_local = "/tmp/processamento_inventario_final"
arquivo_zip_base = "/tmp/inventario_2026"

if os.path.exists(caminho_local):
    shutil.rmtree(caminho_local)
os.makedirs(caminho_local)

print("1. Gerando arquivos Excel na memória temporária...")

# --- 2. GERAÇÃO DOS ARQUIVOS (PANDAS) ---
count = 0
for nomeco, df_pandas_group in df_selected_dict.items():
    nome_seguro = str(nomeco).replace("/", "-").replace(":", "").strip()
    caminho_arquivo = f"{caminho_local}/Inventario_{nome_seguro}.xlsx"
    
    # df_pandas_group já é um DataFrame do Pandas, não precisa de .toPandas()
    df_pandas_group.to_excel(caminho_arquivo, index=False)
    count += 1

print(f"   -> {count} arquivos gerados.")

# --- 3. COMPACTAÇÃO ---
print("2. Compactando...")
shutil.make_archive(arquivo_zip_base, 'zip', caminho_local)
caminho_zip_final = arquivo_zip_base + ".zip"

# --- 4. PREPARANDO DOWNLOAD DIRETO ---
print("3. Preparando download direto...")
with open(caminho_zip_final, "rb") as f:
    zip_data = f.read()
    b64_zip = base64.b64encode(zip_data).decode()

# --- 5. GERAR BOTÃO ---
html_button = f"""
<div style="text-align:center; margin-top:20px; font-family: sans-serif;">
    <div style="background-color:#e8f5e9; padding:20px; border-radius:10px; border: 1px solid #4caf50;">
        <h3 style="color:#2e7d32;">✅ Pronto! Processamento Concluído Localmente.</h3>
        <p>Arquivo zip gerado com sucesso.</p>
        <br>
        <a href="data:application/zip;base64,{b64_zip}" download="inventario_2026.zip">
            <button style="
                background-color:#2e7d32; 
                color:white; 
                padding:15px 30px; 
                font-size:16px; 
                border-radius:5px; 
                border:none; 
                cursor:pointer; 
                font-weight: bold;
                box-shadow: 0px 4px 6px rgba(0,0,0,0.2);">
                📥 CLIQUE AQUI PARA BAIXAR
            </button>
        </a>
        <p style="color:gray; font-size:12px; margin-top:15px;">Salvar em: D:\\dougl\\Documents\\CCB_Patrimonio\\painelAtivoImob\\inventario_2026</p>
    </div>
</div>
"""

shutil.rmtree(caminho_local)
os.remove(caminho_zip_final)

ipy_display(HTML(html_button))

1. Gerando arquivos Excel na memória temporária...
   -> 51 arquivos gerados.
2. Compactando...
3. Preparando download direto...